In [1]:
from data_specific import *
import model_creating, metrics
import torch, torch.nn as nn
import inference

In [2]:
device = torch.device(f'cuda:1')

In [3]:
# get image
data = Data.Diseases
ds_create_fn = get_ds_create_fn(data)
val_ds = ds_create_fn(trn_augm=None, is_demo=False, fold=None, size=448, only_val=True)
img = val_ds.imgs[val_ds.idxs[0]]

Using datasets:  gsa, ulb, atlas_derm, hellenic, dermnetnz
Hadling 7682 data instances


  0%|          | 0/1537 [00:00<?, ?it/s]

In [4]:
# load models
m = model_creating.load_model('logs/weights/run_20210606_133148', get_num_classes(data), device)
fldrs = ['logs/weights/run_20210606_133148',
         'logs/weights/run_20210606_133109',
         'logs/weights/run_20210606_133100']
models = [model_creating.load_model(fldr, get_num_classes(data), device) for fldr in fldrs]

In [5]:
class_mode = get_class_mode(data)

In [6]:
inference.vanilla_predict(device, img, m, class_mode)

array([[9.0617714e-03, 2.3503024e-02, 9.0526586e-04, 6.2592393e-01,
        4.1873446e-03, 3.4166786e-03, 2.8168413e-04, 4.1375219e-04,
        9.3828082e-02, 1.3002114e-03, 1.9172738e-01, 1.2095366e-04,
        3.7416938e-04, 4.3113928e-04, 2.7113544e-02, 4.0981910e-04,
        2.4644292e-03, 7.1105463e-03, 8.0710591e-04, 6.6192057e-03]],
      dtype=float32)

In [7]:
inference.TTA_predict(device, img, m, class_mode, 'hflip', 6)

array([[7.3614377e-03, 1.3957809e-02, 1.4502389e-03, 6.0488147e-01,
        1.0500483e-02, 3.4407403e-03, 5.6452624e-04, 4.6124440e-04,
        6.8226367e-02, 2.4072181e-03, 2.2133674e-01, 1.3262003e-04,
        3.9814838e-04, 7.0465112e-04, 4.8161879e-02, 5.4548820e-04,
        2.4087222e-03, 5.1277592e-03, 7.0529245e-04, 7.2271973e-03],
       [7.3614377e-03, 1.3957809e-02, 1.4502389e-03, 6.0488147e-01,
        1.0500483e-02, 3.4407403e-03, 5.6452624e-04, 4.6124440e-04,
        6.8226367e-02, 2.4072181e-03, 2.2133674e-01, 1.3262003e-04,
        3.9814838e-04, 7.0465112e-04, 4.8161879e-02, 5.4548820e-04,
        2.4087222e-03, 5.1277592e-03, 7.0529245e-04, 7.2271973e-03],
       [9.0617752e-03, 2.3503035e-02, 9.0526580e-04, 6.2592387e-01,
        4.1873441e-03, 3.4166784e-03, 2.8168413e-04, 4.1375216e-04,
        9.3828082e-02, 1.3002119e-03, 1.9172737e-01, 1.2095365e-04,
        3.7416935e-04, 4.3113946e-04, 2.7113542e-02, 4.0981924e-04,
        2.4644290e-03, 7.1105459e-03, 8.071058

In [8]:
inference.ensemble_predict(device, img ,models, class_mode)

array([[9.06177144e-03, 2.35030241e-02, 9.05265857e-04, 6.25923932e-01,
        4.18734457e-03, 3.41667864e-03, 2.81684130e-04, 4.13752190e-04,
        9.38280821e-02, 1.30021141e-03, 1.91727385e-01, 1.20953657e-04,
        3.74169380e-04, 4.31139284e-04, 2.71135438e-02, 4.09819098e-04,
        2.46442924e-03, 7.11054634e-03, 8.07105913e-04, 6.61920570e-03],
       [6.01246301e-03, 7.84566328e-02, 2.76651024e-03, 2.73052067e-01,
        5.38853556e-02, 2.91229431e-02, 2.74779107e-02, 6.08229032e-03,
        3.01038951e-01, 2.35580746e-03, 2.33612284e-02, 1.05303584e-03,
        4.16968204e-03, 6.30937750e-03, 2.50401106e-02, 2.63778050e-03,
        1.13752000e-02, 9.58913006e-03, 1.01774018e-02, 1.26036137e-01],
       [3.37326713e-02, 1.84919890e-02, 1.81467645e-02, 1.29326433e-01,
        5.50648794e-02, 1.48002654e-02, 3.04586180e-02, 5.48481662e-03,
        2.66574353e-01, 1.10075325e-02, 8.24164078e-02, 5.36673702e-03,
        8.59242305e-03, 4.33312310e-03, 8.04769397e-02, 1.1218